#!/usr/bin/env bash
# ──────────────────────────────────────────────
# OpenBao → secrets/litellm-secrets.env 동기화
#
# 인증: AppRole (read-only). root token은 사용하지 않는다.
# 흐름:
#   secrets/openbao-approle.env  (role_id + secret_id, 01-init이 생성)
#         ↓ AppRole 로그인
#   OpenBao(secret/litellm/USERnn_OPENAI_KEY)  ← 관리자가 set-openai-key.sh로 적재
#         ↓ (이 스크립트, KV read)
#   secrets/litellm-secrets.env  (LiteLLM 컨테이너 env_file로 주입)
#
# 이 스크립트가 하는 일:
#   1) AppRole 로그인 → 단명 토큰 발급
#   2) user01..user10 슬롯 KV read (없으면 placeholder 적재 1회)
#   3) secrets/litellm-secrets.env 갱신 (chmod 600)
# ──────────────────────────────────────────────
set -euo pipefail

: "${BASE_DIR:?BASE_DIR not set}"

INIT_KEYS_FILE="${BASE_DIR}/openbao/init-keys.json"
SECRETS_DIR="${BASE_DIR}/secrets"
APPROLE_FILE="${SECRETS_DIR}/openbao-approle.env"
SECRETS_FILE="${SECRETS_DIR}/litellm-secrets.env"
BAO_ADDR_INTERNAL="http://127.0.0.1:8200"

log() { echo "  [secrets] $*"; }

if [[ ! -f "$APPROLE_FILE" ]]; then
  echo "  [secrets] ERROR: ${APPROLE_FILE} not found. Run ./start.sh first to bootstrap AppRole." >&2
  exit 1
fi

# AppRole 자격증명 로드
# shellcheck disable=SC1090
source "$APPROLE_FILE"

if [[ -z "${OPENBAO_LITELLM_ROLE_ID:-}" || -z "${OPENBAO_LITELLM_SECRET_ID:-}" ]]; then
  echo "  [secrets] ERROR: AppRole credentials missing in ${APPROLE_FILE}" >&2
  exit 1
fi

# ── 1. AppRole 로그인 ──
LITELLM_TOKEN=$(docker exec -e BAO_ADDR="$BAO_ADDR_INTERNAL" openbao \
  bao write -format=json auth/approle/login \
  role_id="$OPENBAO_LITELLM_ROLE_ID" \
  secret_id="$OPENBAO_LITELLM_SECRET_ID" 2>/dev/null \
  | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d['auth']['client_token'])
except Exception:
    pass
")

if [[ -z "$LITELLM_TOKEN" ]]; then
  echo "  [secrets] ERROR: AppRole login failed. AppRole may need re-bootstrap (./start.sh)." >&2
  exit 1
fi

bao_litellm() {
  docker exec -e BAO_TOKEN="$LITELLM_TOKEN" -e BAO_ADDR="$BAO_ADDR_INTERNAL" openbao bao "$@"
}

# placeholder 적재용 root (AppRole은 read-only)
bao_root_kv_put_placeholder() {
  local var_name="$1" placeholder="$2"
  local root_token
  root_token=$(python3 -c "import json; print(json.load(open('${INIT_KEYS_FILE}'))['root_token'])")
  docker exec -e BAO_TOKEN="$root_token" -e BAO_ADDR="$BAO_ADDR_INTERNAL" openbao \
    bao kv put "secret/litellm/${var_name}" key="$placeholder" >/dev/null
}

# ── 2. 동기화 ──
log "Syncing OpenBao → ${SECRETS_FILE} via AppRole token..."

mkdir -p "$SECRETS_DIR"
chmod 700 "$SECRETS_DIR"

TMP_FILE=$(mktemp)
trap "rm -f ${TMP_FILE}" EXIT

cat > "$TMP_FILE" <<'EOF'
# LiteLLM OpenAI Keys — rendered from OpenBao via AppRole
# Generated by scripts/02-load-secrets.sh — do not edit manually.
EOF

PLACEHOLDER_COUNT=0
REAL_COUNT=0

for i in 01 02 03 04 05 06 07 08 09 10; do
  VAR_NAME="USER${i}_OPENAI_KEY"

  # 슬롯이 OpenBao에 없으면 placeholder 1회 적재 (실 키 보호 — read 시 아무 영향 없음)
  if ! bao_litellm kv get "secret/litellm/${VAR_NAME}" >/dev/null 2>&1; then
    bao_root_kv_put_placeholder "$VAR_NAME" "sk-proj-poc-user${i}-placeholder-not-set-yet"
  fi

  VAL=$(bao_litellm kv get -format=json "secret/litellm/${VAR_NAME}" \
    | python3 -c "
import sys, json
try:
    d = json.load(sys.stdin)
    print(d['data']['data'].get('key', ''))
except Exception:
    print('')
" 2>/dev/null || echo "")

  if [[ -z "$VAL" ]]; then
    log "  ✗ Failed to read ${VAR_NAME} from OpenBao"
    exit 1
  fi

  if [[ "$VAL" == *placeholder* ]]; then
    PLACEHOLDER_COUNT=$((PLACEHOLDER_COUNT + 1))
  else
    REAL_COUNT=$((REAL_COUNT + 1))
  fi

  printf '%s=%s\n' "$VAR_NAME" "$VAL" >> "$TMP_FILE"
done

mv "$TMP_FILE" "$SECRETS_FILE"
chmod 600 "$SECRETS_FILE"

log "  ✓ Rendered 10 slots → ${SECRETS_FILE}  (real=${REAL_COUNT}, placeholder=${PLACEHOLDER_COUNT})"
if [[ $PLACEHOLDER_COUNT -gt 0 ]]; then
  log "  ! ${PLACEHOLDER_COUNT} slot(s) still on placeholder."
  log "    Set real OpenAI key:  ./scripts/set-openai-key.sh userNN sk-proj-..."
fi
